# Zookeeper Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper:3.5.7
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "2"

---
# Zookeeper Service
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: kafka
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app: zookeeper
  clusterIP: None  # Headless service for direct pod-to-pod communication

---
# Kafka Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka:latest
          ports:
            - containerPort: 9093
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: INSIDE-KAFKA://kafka:9093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL
              value: PLAINTEXT
            - name: KAFKA_LISTENER_NAME_INSIDE
              value: INSIDE
            - name: KAFKA_LISTENER_PORT
              value: "9093"
            - name: KAFKA_LISTENER_INTERNAL
              value: INSIDE
            - name: KAFKA_LISTENER_MODE
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
              value: "6000"

---
# Kafka Service
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 9093
      name: kafka
  selector:
    app: kafka
  clusterIP: None  # Headless service for direct pod-to-pod communication

